# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-05 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='留言')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
