# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=20, verbose_name='服务器名')),
                ('ip', models.GenericIPAddressField(verbose_name='ip地址')),
                ('port', models.CharField(max_length=5, verbose_name='远程端口')),
                ('region', models.CharField(blank=True, max_length=20, null=True, verbose_name='地区')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('encrypt_method', models.CharField(max_length=30, verbose_name='加密方式')),
                ('qr_code', models.FilePathField(blank=True, path='F:\\project\\Anonymous_message\\media/QC', recursive=True, verbose_name='QC路径')),
            ],
            options={
                'verbose_name': 'SS',
                'verbose_name_plural': 'SS',
            },
        ),
    ]
