# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='ip地址')),
                ('port', models.CharField(max_length=5, verbose_name='端口')),
                ('region', models.CharField(blank=True, max_length=20, null=True, verbose_name='地区')),
            ],
            options={
                'verbose_name': 'SS',
                'verbose_name_plural': 'SS',
            },
        ),
    ]
