# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ss'),
    ]

    operations = [
        migrations.AddField(
            model_name='ss',
            name='encrypt_method',
            field=models.CharField(default='NULL', max_length=30, verbose_name='加密方式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ss',
            name='password',
            field=models.CharField(default='NULL', max_length=30, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ss',
            name='qr_code',
            field=models.FilePathField(allow_files='*.png', default='NULL', path='F:\\project\\Anonymous_message\\media/QR', verbose_name='QC路径'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ss',
            name='server_name',
            field=models.CharField(default='NULL', max_length=20, verbose_name='服务器名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ss',
            name='port',
            field=models.CharField(max_length=5, verbose_name='远程端口'),
        ),
    ]
