# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ss'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='快照url')),
                ('file_path', models.FilePathField(blank=True, path='/home/ross/work/project/Anonymous_message/media/page_shot', recursive=True, verbose_name='快照路径')),
                ('shot_name', models.CharField(max_length=30, verbose_name='快照名')),
            ],
        ),
        migrations.AlterField(
            model_name='ss',
            name='qr_code',
            field=models.FilePathField(blank=True, path='/home/ross/work/project/Anonymous_message/media/QC', recursive=True, verbose_name='QC路径'),
        ),
    ]
