# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-05 12:06
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170305_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, verbose_name='留言时间'),
        ),
    ]
