# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170515_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ss',
            name='qr_code',
            field=models.FilePathField(allow_files='*.png', path='F:\\project\\Anonymous_message\\media/QR', recursive=True, verbose_name='QC路径'),
        ),
    ]
